select * from customer;
--1.total revenue generated by male vs female
select gender,sum(purchase_amount)as revenue
from customer
group by gender;

--2.which customers used a discount but still spent more than the average purchase amount

select customer_id
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer);

--3.which are the top 5 product with the highest average review rating

select item_purchased,avg(review_rating)
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4. compare the average purchase_amount between standard and express shipping

select shipping_type,round(avg(purchase_amount),2)
from customer
where shipping_type in ('Express','Standard')
group by shipping_type;

--5.do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscribers

select subscription_status,sum(purchase_amount),avg(purchase_amount)
from customer
group by subscription_status;


--6.which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased ,
round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(item_purchased),2) as percentage
from customer
group by item_purchased
order by percentage desc limit 5;

--7. segment customers into New,Returning and Loyal based on thier total number of previous purchases,and show the count of each segment

with customers as (select customer_id,previous_purchases,
case when previous_purchases=1 then 'New' 
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as Customer_segment 
from customer)

select Customer_segment,count(Customer_segment) as Segment_count
from customers
group by Customer_segment;

--8. what are the top 3 most purchased products within each category 

with item_ranks as(select item_purchased,category,count(item_purchased)as no_of_product,
row_number() over(partition by category order by count(item_purchased) desc) as item_rank
from customer 
group by category,item_purchased)

select * from item_ranks 
where item_rank<4;

--9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe

select subscription_status,count(customer_id) as no_of_customers
from customer
where previous_purchases>5
group by subscription_status;

--10. what is revenue contribution of each age group 

select age_group,sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc;


